spring.http.converters.preferred-json-mapper: gson

server:
  port: 8080

management:
  port: 8081
  context-path: /management
  security:
    enabled: false

security:
  basic:
    enabled: false
spring:
  application:
     name: activiti
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/activiti
     username: pos-frontend
     password: pos-frontend
     maximum-pool-size: 50
     connection-timeout: 10000
     idle-timeout: 30000
  jpa:
     hibernate:
        ddl-auto: create-drop

activemq:
  brokerUrl: tcp://localhost:61616
  topic:
    notify: notify.topic


logging:
  level:
    root: INFO
    org.apache.camel: INFO